mode: required
method: legacy
id: browser

labels:
  step: "Browser"

default: brave-origin

items:
  - id: firefox
    package: firefox
    name: Firefox
    description: >
      Mozilla's open-source browser.
    screenshot: "browser-firefox.png"

  - id: brave-origin
    package: brave-origin-bin
    name: Brave Origin
    description: >
      Chromium-based browser with a modern UX and a focus on privacy and security.
      Has a built-in ad blocker.
      Default browser for Frog Linux.
    screenshot: "browser-brave-origin.png"

  - id: zen
    package: zen-browser-bin
    name: Zen
    description: >
      Firefox-based browser with a modern UX.
    screenshot: "browser-zen.png"

  - id: chromium
    package: chromium
    name: Chromium
    description: >
      Google's open-source browser.
    screenshot: "browser-chromium.png"

  - id: helium
    package: helium-browser-bin
    name: Helium
    description: >
      Lightweight chromium-based browser with a minimalist UX and a focus on privacy and security.
      Has a built-in ad blocker. 
      Still in beta.
    screenshot: "browser-helium.png"