defaultGroups:
    - users
    - lp
    - video
    - network
    - storage
    - wheel
    - audio

autologinGroup:  autologin
sudoersGroup:    wheel
setRootPassword: false
doAutologin:     true

passwordRequirements:
    minLength: 1
