---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false

requirements:
  requiredRam: 1.0
  check:
    - ram
    - root
    - screen
  required:
    - ram
    - root

geoip:
  style: none
