# Frog Linux — Calamares configuration
# See https://github.com/calamares/calamares/wiki/Configuration

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - packagechooser_browser
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - hwclock
  - initcpiocfg
  - initcpio
  - grubcfg
  - bootloader
  - contextualprocess_browser
  - umount
- show:
  - finished

branding: frog

prompt-install: true
dont-chroot: false
